### ISSUE TITLE
Cannot Trigger RoV 2-11 "Take Wing" Cutscene

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1895]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Beginning Progress:
CoP: 3-3 (Only progress is Ulmia path started by zoning into Northern Sandoria) (Do not progress further during test)
RoV: 2-8 ([The Endless Sky](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-8))
ToAU: 0

1. Begin by progressing to ToAU 12 ([Royal Puppeteer](https://www.bg-wiki.com/ffxi/Aht_Urhgan_Mission_12))
2. Zone to Aht Urgan Whitegate and click the **Imperial Whitegate** to begin and finish RoV2-9 ([Amphau's Light](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-9))
3. Enter **Walahra Temple** and talk to Nadeey to finish RoV 2-10 ([Reunited](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-10))
4. Walk into Sharahat Teahouse to **try** to trigger RoV 2-11 ([Take Wing](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-11)) cutscene. No cutscene triggers.
NOTE: Player's CoP was both A) not at a RoV-pausing point and B) never progressed during these steps.

## Expected behavior

RoV 2-11 cutscene should trigger once the player has entered the trigger area in Sharahat Teahouse.

NOTE: Is https://github.com/LandSandBoat/server/blob/base/scripts/missions/rov/2_11_Take_Wing.lua line 33 requiring [PM 7-5](https://ffxiclopedia.fandom.com/wiki/The_Warrior's_Path?so=search) to be complete here??

**Comment by RAIST5150** [comment]
As I understand it, they are still missing a lot of caps for what triggers different events in the RoV missions.  The comments in some of the RoV scripts note that some things have not been scripted because of this.

Expansion progression can leave some characters unavailable to appear in RoV events, which can stall progression.  That check may be the only known condtion/event correlation documented for this mission at the time it was scripted.

Can confirm that with all of ZM, CoP, and TAU main story completed on xiweb (running base), I was able to push through to log Cauterize when that last batch of RoV missions were added.

**Comment by Dev-Roland** [comment]
> Expansion progression can leave some characters unavailable to appear in RoV events, which can stall progression. That check may be the only known condtion/event correlation documented for this mission at the time it was scripted.

Given that A) Both 2-10 and 2-11 mention no CoP requirement (at-all) in the wikis and B) 2-10 has no such check but 2-11 does, there seems to be a discrepancy in that this CoP requirement that was coded into 2-11. That is, as far as I can tell, and I'm very unfamiliar with the library here so I can definitely be wrong.

Please note that I did post my CoP progress in the repro steps so that it can be known during testing.

**Comment by RAIST5150** [comment]
Earlier in the RoV mission pages though, it notes that if you progress CoP to a certain point, it will stall RoV progression until you move CoP further... like, all the way to Dawn.  Forget exactly where it was, but it noted something specific to availability of Ulmia, Prishe, and Tenzen IIRC.

EDIT:
It becomes a recurring theme after Volto Oscuro on the xiclopedia wiki.  A lot of vague and unknown details, but a good bit of talk about how characters will react depending on the state of CoP progression... and they are missing captures of some those triggers/events.

https://ffxiclopedia.fandom.com/wiki/Ring_My_Bell

https://github.com/LandSandBoat/server/blob/base/scripts/missions/rov/1_18_Ring_My_Bell.lua

**Comment by RolandJ2** [comment]
> Earlier in the RoV mission pages though, it notes that if you progress CoP to a certain point, it will stall RoV progression until you move CoP further... like, all the way to Dawn. Forget exactly where it was, but it noted something specific to availability of Ulmia, Prishe, and Tenzen IIRC.

I mentioned, just for the reason you just quoted, my CoP progress so that reviewers can confirm that I did not go to the point that is supposed to block RoV progress (AFAIK). My CoP has not progressed since the previous two CSs, yet the previous two CSs went through fine. **This** CS for 2-12 seems to be the odd man out.

**Comment by Dev-Roland** [comment]
I just supplemented my repro steps with more details regarding CoP and RoV progression during the test.
You can also reference https://forum.square-enix.com/ffxi/threads/47983-What-should-I-do-if-I-can%E2%80%99t-progress-in-Rhapsodies-of-Vana%E2%80%99diel

The more I read the more it seems to me that A) the wikis are confusing on this scenario (lol) and B) the code for RoV 2-11 **seems** to have an LSB-exclusive requirement rather than a retail-like requirement (it requires the **completion** of a CoP not mentioned to have a **completion** (as opposed to a blocking) requirement in the wikis nor in [the official SE post](https://forum.square-enix.com/ffxi/threads/47983-What-should-I-do-if-I-can%E2%80%99t-progress-in-Rhapsodies-of-Vana%E2%80%99diel)) for **this** RoV mission.)

Hopefully I'm just missing something.

**Comment by Dev-Roland** [comment]
To clarify, these are the requirements for RoV 2-11 (Take Wing) found in [SE's official post](https://forum.square-enix.com/ffxi/threads/47983-What-should-I-do-if-I-can%E2%80%99t-progress-in-Rhapsodies-of-Vana%E2%80%99diel):
_(Our code mentions one of the 14 CoP missions in Tenzen's list. By reading the LSB code it appears to be **A)** blocking the CS **until** the user finishes the CoP 7-5 mission not **B)** blocking the cs if the user is **on** the CoP 7-5 mission . If it indeed is performing A then that would seem to be a mistaken requirement (and a strict one compared to retail CoP requirements). If B then I should be getting the CS, right?)_

# 2: Tenzen
Tenzen will not be available if you are currently undertaking one of the following Chains of Promathia missions.
The Rites of Life / Below the Arks / The Mothercrystals / An Invitation West / The Lost City / Distant Beliefs /
An Eternal Melody / Ancient Vows / The Call of the Wyrmking / A Vessel Without a Captain / Desire of Emptiness /
The Warrior’s Path / Garden of Antiquity / When Angels Fall / Dawn
* In Dawn, Tenzen is unavailable until viewing the cutscene for The Chains Fall Free in Lufaise Meadows.

# 3: Aphmau
Aphmau will not be available if you are currently undertaking one of the following Treasures of Aht Urhgan missions.
Land of Sacred Serpents / Immortal Sentries / President Salaheem / Knight of Gold /
Confessions of Royalty / Easterly Winds / Westerly Winds / A Mercenary Life / Undersea Scouting /
Astral Waves / Imperial Schemes / Sweets for the Soul / Teahouse Tumult / Finders Keepers /
Seal of the Serpent / Misplaced Nobility / Bastion of Knowledge / Puppet in Peril / Prevalence of Pirates /
Shades of Vengeance / In the Blood / Sentinels’ Honor / Testing the Waters / Legacy of the Lost /
Gaze of the Saboteur / Path of Blood / Stirrings of War / Allied Rumblings / Unraveling Reason /
Light of Judgment / Path of Darkness / Fangs of the Lion / Nashmeira’s Plea / Ragnarok / Imperial Coronation

**Comment by RAIST5150** [comment]
They are lacking captures for a lot of this, which is needed to code the various triggers/events.

As is noted in many of the RoV scripts, some things have been left out because of this.

Until more of the needed data is captured, progression may be restricted to only the confirmed correlations from the captures.

As such, all RoV is expected to evolve as more captures are submitted/reviewed.

**Comment by FuzzyWereBeast** [comment]
I think this was fixed by #1943

**Comment by Dev-Roland** [comment]
I still do not trigger the CS when I enter the teahouse. I'm still on the same ToAU and CoP missions and, for what it's worth, the only ToAU quest I have active is "The Luck of the Draw".

**Comment by Dev-Roland** [comment]
Without progressing CoP since the original repro steps were authored, I was now able to trigger the CS. Issue fixed.

**Comment by Aeisu** [comment]
Just a note I just got to RoV 1-18 and Have completed all of DAWN for CoP and the door in norg gives me a message saying tenzen is still AWOL. I commented out the restrictions on DAWN in scripts/globals/rhapsodies.lua and that seems to bypass it
