### ISSUE TITLE
🐛 Conquest System Crash Due To Race Condition / SQL Disconnect (Windows Sleep)

### ISSUE THREAD

**Issue by atom0s** [DerpyProjectGroup/topaz#5006]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

  - Windows 11 - 23H2 (22631.2506)

## Branch affected by issue 

  - `base`

## Steps to reproduce

This is a race condition issue that can happen when the SQL connection drops and needs to reconnect, thus it is hard to reproduce reliably. However, this is the general steps taken that can cause it to happen:

  - Fully setup current `base` LSB on a system.
  - Launch `login`, `map` and `world` servers. _(Search server not required.)_
  - Connect to the server at least once with a character, then logout.
  - Put the system to sleep using Windows' built-in sleep mode.
  - Turn the system back on.

At this point, there is a chance the `map` server will crash due to various race conditions.

## Expected behavior

It would be expected that the SQL connection is restored before additional queries are run, or that if a query fails due to the SQL connection being lost, the server would reconnect and attempt the same query again in some manner before attempting to process a null return.

## Detailed Information

There is a [somewhat] high chance of the `map` server crashing when waking a system from sleep if the servers were running at the time the system was put to sleep. This issue is due to race conditions where ZMQ messages and SQL queries can be attempted before the SQL connection is given a chance to recover/reconnect. 

The current observed crash related to this race condition is with the Conquest system. It is possible that the `map` server will receive a conquest influence update message and attempt to process this message before the SQL connection is properly checked and reconnected.

Here is the call stack of what crashed:

```
=== Call stack ===
Address           Frame             Function
00007FFAA03F565C  000000DF85579710  RaiseException+6C ()
00007FF6BF52A0FC  000000DF85579740  WheatyExceptionReport::WheatyCrtHandler+2C (..\LandSandBoat-server\src\common\WheatyExceptionReport.cpp, line 392)
00007FF9BD9D81A6  000000DF855797B0  _invalid_parameter+196 ()
00007FF9BD9D8070  000000DF85579830  _invalid_parameter+60 ()
00007FF6BFA99E3E  000000DF8557A600  ConquestData::getInfluence+2AE (..\LandSandBoat-server\src\map\conquest_data.cpp, line 74)
00007FF6BFA9C42F  000000DF8557A6E0  conquest::GetInfluenceGraphics+4F (..\LandSandBoat-server\src\map\conquest_system.cpp, line 313)
00007FF6BFA9D066  000000DF8557A790  `conquest::HandleInfluenceUpdate'::`5'::<lambda_1>::operator()+66 (..\LandSandBoat-server\src\map\conquest_system.cpp, line 517)
00007FF6BFA6F924  000000DF8557A8F0  zoneutils::ForEachZone+A4 (..\LandSandBoat-server\src\map\utils\zoneutils.cpp, line 1169)
00007FF6BFA9CFC5  000000DF8557A9F0  conquest::HandleInfluenceUpdate+105 (..\LandSandBoat-server\src\map\conquest_system.cpp, line 507)
00007FF6BFA9BD50  000000DF8557ABF0  conquest::HandleZMQMessage+360 (..\LandSandBoat-server\src\map\conquest_system.cpp, line 99)
00007FF6BFACFBCA  000000DF8557EAD0  message::parse+3E3A (..\LandSandBoat-server\src\map\message.cpp, line 791)
00007FF6BFAD08F8  000000DF8557EBF0  message::handle_incoming+78 (..\LandSandBoat-server\src\map\message.cpp, line 848)
00007FF6BFABDF33  000000DF8557F3A0  do_sockets+43 (..\LandSandBoat-server\src\map\map.cpp, line 500)
00007FF6BF4C2F17  000000DF8557F8D0  main+2B7 (..\LandSandBoat-server\src\common\kernel.cpp, line 274)
00007FF6BFBE3509  000000DF8557F920  invoke_main+39 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 79)
00007FF6BFBE345E  000000DF8557F990  __scrt_common_main_seh+12E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 288)
00007FF6BFBE331E  000000DF8557F9C0  __scrt_common_main+E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 331)
00007FF6BFBE357E  000000DF8557F9F0  mainCRTStartup+E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp, line 17)
00007FFAA17F257D  000000DF8557FA20  BaseThreadInitThunk+1D ()
00007FFAA306AA58  000000DF8557FAA0  RtlUserThreadStart+28 ()
```

The message in question is:

  - `MSG_WORLD2MAP_REGIONAL_EVENT` -> `REGIONAL_EVT_MSG_CONQUEST`

The inner message type is:

  - `CONQUEST_WORLD2MAP_INFLUENCE_POINTS`

The `world` server can raise this message to the map server with invalid or no data because the SQL connection has been lost and did not recover prior to the influence data being requested from the database via:

  - https://github.com/LandSandBoat/server/blob/4d9973f120e470aa874524df5bec81c07e6843c1/src/world/conquest_system.cpp#L98
  - https://github.com/LandSandBoat/server/blob/4d9973f120e470aa874524df5bec81c07e6843c1/src/world/conquest_system.cpp#L267

When this race condition happens, the `map` server will then clear the `influences` vector inside of `ConquestData` which leaves it open to being indexed without any error checking in several of the calls within the entire https://github.com/LandSandBoat/server/blob/base/src/map/conquest_data.cpp file.

The `world` server can also be observed printing the following when this happens:

```
[10/04/23 20:09:38:045][world][error] Query: SELECT sandoria_influence, bastok_influence, windurst_influence, beastmen_influence FROM conquest_system; (SqlConnection::QueryStr:320)
[10/04/23 20:09:38:053][world][error] mysql_real_query: SQL_ERROR: Lost connection to server during query (2013) (SqlConnection::QueryStr:321)
```

**Comment by zach2good** [comment]
Have you noticed this happening anymore? This should be fixed in both the old and new db system now

**Comment by atom0s** [comment]
I can confirm that this is still an issue and is still crashing in the same location. There is more output from the server in regard to SQL failures now, but the server will ultimately crash in the same location upon waking the system up and attempting to connect a character to it.

This appears to still be an issue that goes hand-in-hand with the additional private report I made to you the other evening regarding the SQL connection still never properly reconnecting during this kind of condition. The recent pull to attempt to fix this (#6299) does not appear to be working for this situation still and will end up with the same crash as I initially reported here.

For this most recent test, I pulled latest as of last night, rebuilt and followed the same steps I outlined above to 'prep' the server for testing. _(Rebuilt from latest source, started the servers, connected a character once to ensure everything worked fine and logged the character out. Then put the system to sleep (closed the lid) while the servers were still running.)_ This morning, I woke the system back up from sleep then attempted to connect a character and got the same results as before with a bit more output.

First, this is the output from the server just before putting the system to sleep to show normal operation:

```
[10/09/24 04:09:37:010][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 04:09:38:402][map][debug] UpdateGuildsStock is finished (guildutils::UpdateGuildsStock:151)
[10/09/24 04:09:38:402][map][debug] Player playtime saving finished (zoneutils::SavePlayTime:103)
[10/09/24 04:12:01:046][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 04:13:04:796][map][info] CTaskMgr Active Tasks: 193 (map_garbage_collect:1395)
[10/09/24 04:13:04:874][map][info] Garbage Collected (Full) (luautils::garbageCollectFull:406)
[10/09/24 04:13:04:874][map][info] Current State Top: 0, Total Memory Used: 47526kb -> 47441kb (luautils::garbageCollectFull:407)
[10/09/24 04:14:25:813][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 04:16:49:033][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 04:19:13:000][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 04:21:37:286][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
```
_Time here is 4:21am PST._

The server was functional without issue at this point, just after this last message my system was put to sleep by closing the lid.

This afternoon, when I was able to finally sit at my system, I awoke it from sleep by opening the lid and pressing the power button. The server immediately reported problems (expected ones in this case) of being 'suspended' for a long period of time which resulted in:

```
[10/09/24 12:47:31:134][map][critical] Process main tick has taken 2000ms or more. (main::<lambda_1>::operator ():256)
[10/09/24 12:47:31:510][map][info] (C) Pinging SQL server to keep connection alive (SqlConnection::TryPing:244)
[10/09/24 12:47:31:513][map][warn] DB thread ID has changed. You have been reconnected. (SqlConnection::TryPing:256)
[10/09/24 12:47:31:638][map][info] CTaskMgr Active Tasks: 193 (map_garbage_collect:1395)
[10/09/24 12:47:31:722][map][info] Garbage Collected (Full) (luautils::garbageCollectFull:406)
[10/09/24 12:47:31:722][map][info] Current State Top: 0, Total Memory Used: 47511kb -> 47445kb (luautils::garbageCollectFull:407)
[10/09/24 12:47:31:744][map][info] (C++) Pinging database to keep connection alive (ping_connection::<lambda_1>::operator ():44)
[10/09/24 12:47:31:744][map][error] Database connection is invalid, attempting to reconnect... (ping_connection::<lambda_1>::operator ():49)
[10/09/24 12:48:00:348][map][debug] UpdateGuildsStock is finished (guildutils::UpdateGuildsStock:151)
[10/09/24 12:48:00:348][map][debug] Player playtime saving finished (zoneutils::SavePlayTime:103)
[10/09/24 12:48:02:530][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
```

Watchdog fails due to the long timeout (I have it disabled to not crash the server though) as expected, the SQL connection notices things are wrong and attempts to reconnect. There is nothing else reported here stating if it did or did not reconnect and the last few messages make it seem like the database connection was restored and working, but that is not the case.

Following this, I attempt to connect to the server with my character and get the following:

```
[10/09/24 12:48:26:134][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:48:26:134][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:48:26:134][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
[10/09/24 12:48:28:138][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:48:28:138][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:48:28:138][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
[10/09/24 12:48:30:144][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:48:30:144][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:48:30:144][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
[10/09/24 12:48:32:154][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:48:32:154][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:48:32:154][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
[10/09/24 12:48:34:163][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:48:34:163][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:48:34:163][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
[10/09/24 12:48:36:173][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:48:36:173][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:48:36:173][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
```

This will repeat the entire time the character is stuck in the 'Downloading data..' screen until it times out. Once it fully times out the server then reports:

```
[10/09/24 12:49:10:270][map][error] Query Failed: SELECT charid FROM chars WHERE charid = (?) LIMIT 1 (db::preparedStmt::<lambda_1>::operator ():208)
[10/09/24 12:49:10:270][map][error] (conn=2375) Server has gone away (db::preparedStmt::<lambda_1>::operator ():209)
[10/09/24 12:49:10:270][map][error] recv_parse: Cannot load charid 1 (recv_parse:775)
[10/09/24 12:49:31:515][map][warn] map_cleanup: WITHOUT CHAR timed out, session closed on this process (map_cleanup:1335)
[10/09/24 12:50:26:366][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
```

The server, at this point, still has not crashed yet. The `MSG_WORLD2MAP_REGIONAL_EVENT` message will get received a few more times here until it will ultimately crash about 10 minutes later sitting idle in this state:

```
[10/09/24 12:49:31:515][map][warn] map_cleanup: WITHOUT CHAR timed out, session closed on this process (map_cleanup:1335)
[10/09/24 12:50:26:366][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 12:52:50:342][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 12:55:14:355][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 12:57:38:546][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[10/09/24 13:00:02:529][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\vector(1899) : Assertion failed: vector subscript out of range
```

The actual crash block of the log looks like this:

```
=====================================================
!!! CRASH !!!
Exception code: C0000005 (ACCESS_VIOLATION)
Fault address: 00007FF8E6235B0C 01:0000000000064B0C
Process Name: X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\xi_map.exe --ip 127.0.0.1 --port 54230
Full crash report: X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\dmp\xi_map.exe_9-10_13-0-2.log
Memory dump: X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\dmp\xi_map.exe_9-10_13-0-2.dmp
Time of crash: 2024/10/09 13:00:02
Process Uptime: 20 hours
Processor: 13th Gen Intel(R) Core(TM) i9-13980HX
Number Of Threads: 32
OS: Windows 10 Professional (Version 10.0, Build 22631)
Process Memory Usage: 773MiB / 65536MiB
Git Branch: base
Git Commit Subject: Merge pull request #6331 from LandSandBoat/September-2024-ID-updates
Git SHA: e66c5dac16
Git Date: Tue Oct 8 03:15:44 2024
=====================================================
=== Backtrace ===
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720018)
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720019)
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720020)
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720021)
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720022)
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720023)
CZoneEntities::ZoneServer: NPC: Disjoined_One (17720024)
CZoneEntities::ZoneServer: NPC: blank (17720025)
CZoneEntities::ZoneServer: NPC: blank (17720026)
CZoneEntities::ZoneServer: NPC: Ephemeral_Moogle (17720027)
CZoneEntities::ZoneServer: NPC: Wolden-Bolden (17720028)
CZoneEntities::ZoneServer: NPC: Enigmatic_Footprints (17720029)
CZoneEntities::ZoneServer: NPC: Layer_Reserve (17720030)
CZoneEntities::ZoneServer: NPC: AMAN_Validator (17720031)
CZoneEntities::ZoneServer: NPC: AMAN_Liaison (17720032)
CZoneEntities::ZoneServer: NPC: RepairerMoogle (17720033)
=====================================================
=== Call stack ===
Address           Frame             Function
00007FF8E6235B0C  00000058961792B0  RaiseException+6C ()
00007FF62385412C  00000058961792E0  WheatyExceptionReport::WheatyCrtHandler+2C (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\common\WheatyExceptionReport.cpp, line 391)
00007FF8741681A6  0000005896179350  _invalid_parameter+196 ()
00007FF874168070  00000058961793D0  _invalid_parameter+60 ()
00007FF623E215CB  000000589617A1C0  ConquestData::getInfluence+2DB (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\conquest_data.cpp, line 71)
00007FF623E23C2F  000000589617A2A0  conquest::GetInfluenceGraphics+4F (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\conquest_system.cpp, line 313)
00007FF623E248C6  000000589617A350  `conquest::HandleInfluenceUpdate'::`5'::<lambda_1>::operator()+66 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\conquest_system.cpp, line 517)
00007FF623DF7BE6  000000589617A4B0  zoneutils::ForEachZone+A6 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\utils\zoneutils.cpp, line 1178)
00007FF623E24827  000000589617A5B0  conquest::HandleInfluenceUpdate+107 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\conquest_system.cpp, line 507)
00007FF623E23552  000000589617A7B0  conquest::HandleZMQMessage+362 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\conquest_system.cpp, line 99)
00007FF623E59571  000000589617EF30  message::parse+40A1 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\message.cpp, line 798)
00007FF623E5A849  000000589617F050  message::handle_incoming+79 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\message.cpp, line 877)
00007FF623E47943  000000589617F820  do_sockets+43 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\map\map.cpp, line 542)
00007FF6237EE3D8  000000589617FD50  main+2B8 (X:\SourceCode\GitHub\atom0s\FFXI\LandSandBoat-server\src\common\kernel.cpp, line 276)
00007FF623F838C9  000000589617FDA0  invoke_main+39 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 79)
00007FF623F83812  000000589617FE10  __scrt_common_main_seh+132 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 288)
00007FF623F836CE  000000589617FE40  __scrt_common_main+E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 331)
00007FF623F8393E  000000589617FE70  mainCRTStartup+E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp, line 17)
00007FF8E7C7257D  000000589617FEA0  BaseThreadInitThunk+1D ()
00007FF8E8D2AA58  000000589617FF20  RtlUserThreadStart+28 ()

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

**Comment by atom0s** [comment]
Status update on this now that its been a few months and a lot more changes have happened to the SQL handling since my above reports. At this time, this now appears to be fixed and working as expected. I pulled latest, as of 8 days ago, and have had my servers running in the background on my laptop constantly. Over the last 7-8 days my laptop has been put to sleep and reawoken around 12-15 times.

The servers will report the SQL connection dropping but they will now properly reconnect when a client attempts to connect to the server. This now looks like:

```
-- Laptop put to sleep here..
[01/14/25 03:12:02:511][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)
[01/14/25 03:14:27:245][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (21) from message server (message::parse:90)

-- Laptop woken up here..
[01/14/25 16:44:18:512][map][info] (C) Pinging SQL server to keep connection alive (SqlConnection::TryPing:245)
[01/14/25 16:44:18:514][map][warn] DB thread ID has changed. You have been reconnected. (SqlConnection::TryPing:257)
[01/14/25 16:44:18:579][map][info] CTaskMgr Active Tasks: 192 (map_garbage_collect:1394)
```

The next day, doing the same thing and eventually connecting to the server again shows:

```
[01/15/25 01:11:21:921][map][info] Connection lost, re-establishing connection and retrying query (attempt 1) (db::preparedStmt::<lambda_1>::operator ():541)
[01/15/25 01:11:21:932][map][debug] Player <Atomos> logging in to zone <230> (charutils::LoadChar:718)
[01/15/25 01:11:21:961][map][debug] CZone:: Southern_San_dOria IncreaseZoneCounter <1> Atomos (CZoneEntities::InsertPC:139)
```

No longer crashes and properly reconnects without issue. Going to close this issue for now as this appears to be fixed and working as expected. Will reopen later if it starts up again.

**Comment by zach2good** [comment]
Hooray!
