### ISSUE TITLE
Auto-target doesn't function reliably

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#870]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When engaged to an enemy, if your camera is facing a currently actively(as in fighting against you/engaged/aggrod) enemy, you should auto-target to them after your current enemy dies. This isn't the case the VAST majority of the time.

https://ffxiclopedia.fandom.com/wiki/Command/autotarget

**Comment by RAIST5150** [comment]
Seems like it may be tied into the potential to hit or something... so long as I am able to swing at the next target then it consistently switches.

(Have been pulling multiple mobs for CP farming).

**Comment by claywar** [comment]
Have you reproduced this with stock LSB?  This issue was solved quite some time ago, and I haven't seen any non-retail behavior.

**Comment by RAIST5150** [comment]
A few times I sheathed my weapon when I pulled a bunch of crabs in Forrett last night, but they were likely just on edge of sight/swinging range, which would make sense I guess. 

Wasn't something on my radar to watch for, so wasn't really paying attention to the specifics.  Otherwise, it seems to be working as it should be lately with everything branch.

**Comment by TeoTwawki** [comment]
> Have you reproduced this with stock LSB? This issue was solved quite some time ago, and I haven't seen any non-retail behavior.

@claywar we're still not as good as retail about auto targettingthe "next mob". Its also worth a mention that retail itself isn't perfect about this and we could potentially be "better than retail" about this. Shouldn't be that hard to look if an aggressive mob is in our sight cone actively smacking us but SE manages to fail it about 1 in 5 tries when I have multiple possible targets (or pick the farthest one -_-).

**Comment by claywar** [comment]
The only reason I asked is that we used to have a bad problem with auto-target even within a facing conal.  This was resolved early this year, and seems to follow behavior I'd expect.

**Comment by ShiyoKozuki** [comment]
Can you link to the commit that fixed this?

**Comment by claywar** [comment]
Happened earlier this year before the rebranding to LSB
